.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.\"
.\" Please adjust this date whenever revising the manpage.
.TH GNANK 1 "February 2006"
.SH NAME
gnank \- Cercador d'horaris de la FIB
.SH SYNOPSIS
.B gnank
.\" .RI [ options ] " files" ...
.SH DESCRIPTION
.\" This manual page documents briefly the
.\" .B gnank
.\" command.
.PP
\fBgnank\fP es un programa creat amb l'objectiu de facilitar la tria
de l'horari dels alumnes de la FIB.
.\" .SH OPTIONS
.\" .TP
.\" .B \-h, \-\-help
.\" Show summary of options.
.\" .TP
.\" .B \-v, \-\-version
.\" Show version of program.
.SH AUTHOR
.B gnank 
was written by Albert Gasset <albert.gasset@gmail.com>.
.PP
This manual page was written by Jorda Polo <jorda@ettin.org>,
for the Debian project (but may be used by others).
